name: Build and publish Janet docker images

on:
  schedule:
    - cron:  '22 1/8 * * *'
  push:
    branches:
    - master

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: run build script
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          ./docker-janet.sh

